apiVersion: apps/v1
kind: Deployment
metadata:
  name: tergos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tergos
  template:
    metadata:
      labels:
        app: tergos
    spec:
      containers:
      - image: okteto.dev/tergos:latest
        name: tergos
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "93a65a8a-1356-4ee4-ab66-53504a4f6466"
        - name: Vless_Path
          value: "/93a65a8a-1356-4ee4-ab66-53504a4f6466-vless"
        - name: Vmess_UUID
          value: "93a65a8a-1356-4ee4-ab66-53504a4f6466"
        - name: Vmess_Path
          value: "/5c301bb8-6c77-41a0-a606-4ba11bbab084-vmess"
        - name: Share_Path
          value: "$Share_Path"
