apiVersion: apps/v1
kind: Deployment
metadata:
  name: korizon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: korizon
  template:
    metadata:
      labels:
        app: korizon
    spec:
      containers:
      - image: okteto.dev/korizon:latest
        name: korizon
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "791802f2-0841-4c57-a604-83468de473f7"
        - name: Vless_Path
          value: "/791802f2-0841-4c57-a604-83468de473f7-vless"
        - name: Vmess_UUID
          value: "791802f2-0841-4c57-a604-83468de473f7"
        - name: Vmess_Path
          value: "/dcc8baa1-0021-4ea7-823b-4bf9f3f0a23d-vmess"
        - name: Share_Path
          value: "$Share_Path"
